export const sample_foods: any[] = [
  {
    id: '1',
    name: 'Pepperoni Pizza',
    cookingTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/images/food-1.jpg',
    tags: ['Fast food', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatballs',
    price: 20,
    cookingTime: '20-30',
    favorite: false,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/images/food-2.jpg',
    tags: ['Slow food', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 5,
    cookingTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/images/food-3.jpg',
    tags: ['Fast food', 'Hamburger'],
  },
  {
    id: '4',
    name: 'French Fries',
    price: 2,
    cookingTime: '15-20',
    favorite: false,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/images/food-4.jpg',
    tags: ['Fast food', 'Fried'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookingTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/images/food-5.jpg',
    tags: ['Slow food', 'Soup'],
  },
  {
    id: '6',
    name: 'Veggie Pizza',
    price: 9,
    cookingTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food-6.jpg',
    tags: ['Fast food', 'Pizza', 'Lunch'],
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'Fast food', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'Slow food', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fried', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'Jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false,
  },
];
